config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  
  get 'focus_to_section/:section_id', to: 'welcome#focus_to_section', as: 'focus_to_section'
  get 'scroll_to_top', to: 'welcome#scroll_to_top', as: 'scroll_to_top'
  
  get 'carousel_scroll/:direction', to: 'posts#carousel_scroll', as: 'carousel_scroll'

  
  get 'sessions/new'
  post 'sessions/create', as: 'sessions'
  delete 'sessions/destroy'
  delete 'sessions/destroy_all_other_sessions', as: 'destroy_all_other_sessions'
  
  get 'pages/toggle_menu', as: 'toggle_menu'

  resources :users
  resources :posts

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  
  validates_uniqueness_of :name
  validates_presence_of :name, length: { minimum: 3 }
  validates_presence_of :password, length: { minimum: 4 }
  validates_confirmation_of :password

  before_create :encrypt_password, :gen_auth_token
  
  def update_token
    self.gen_auth_token
    self.save
  end

  def gen_auth_token
    begin
      self.auth_token = SecureRandom.urlsafe_base64
    end while User.exists? auth_token: self.auth_token
  end

  def self.authenticate name, password
    user = self.find_by_name name
    # if user found and password matches decrypted one saved in db
    if user && user.password == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  private
    def encrypt_password
      if self.password.present?
        self.password_salt = BCrypt::Engine.generate_salt
        self.password = BCrypt::Engine.hash_secret(self.password, self.password_salt)
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user, :browser, :mobile?

  def current_user
    @current_user ||= User.find_by_auth_token(cookies[:auth_token]) if cookies[:auth_token]
  end
  
  def mobile?
    browser.device.mobile? or browser.device.tablet?
  end
  
  def browser
    Browser.new("Some User Agent", accept_language: "en-us")
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def toggle_menu
    # if nav menu is already open and was opened in the last 10 seconds
    if session[:nav_menu_shown].present? and session[:nav_menu_shown_at].to_datetime > 5.second.ago
      @nav_menu_shown = true
      session[:nav_menu_shown] = ''
    else
      @nav_menu_shown = false
      session[:nav_menu_shown] = true
      session[:nav_menu_shown_at] = DateTime.current
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def carousel_scroll
    @carousel_size = 4
    @direction = params[:direction]
    # steps up and down carousel_index
    cookies[:carousel_index] = if @direction.to_sym.eql? :right
      cookies[:carousel_index] = cookies[:carousel_index].to_i + 1
    elsif @direction.to_sym.eql? :left
      cookies[:carousel_index] = cookies[:carousel_index].to_i - 1
    end
    # keeps within limits
    if cookies[:carousel_index].to_i > Post.all.size - @carousel_size
      cookies[:carousel_index] = 0
    elsif cookies[:carousel_index].to_i < 0
      cookies[:carousel_index] = Post.all.size - @carousel_size
    end
    # gets images
    @images = Post.limit(@carousel_size).offset(cookies[:carousel_index].to_i)
    # carousel image to insert with ids
    if @direction == "right"
      @image = @images.last
      @point_to_add = "last"
      @point_to_remove ="first"
    elsif @direction == "left"
      @image = @images.first
      @point_to_add = "first"
      @point_to_remove = "last"
    end
  end
  
  def new
    @post = Post.new
  end
  
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to root_url
    else
      redirect_to :back
    end
  end
  
  private
  
  def post_params
    params.require(:post).permit(:body, :image)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    @user = User.authenticate(params[:login], params[:password])
    if @user
      @user.update_token if @user.auth_token.nil? # stay logged in on multiple devices/browsers
      if params[:remember_me]
        cookies.permanent[:auth_token] = @user.auth_token
      else
        cookies[:auth_token] = @user.auth_token
      end
      cookies.permanent[:logged_in_before] = true
      redirect_to root_url
    else
      redirect_to :back, notice: "Invalid username, email, or password"
    end
  end
  
  def destroy
    if current_user
      current_user.update_token
      cookies.delete(:auth_token)
    end
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    unless current_user
      @user = User.new
    end
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      if params[:remember_me]
        cookies.permanent[:auth_token] = @user.auth_token
      else
        cookies[:auth_token] = @user.auth_token
      end
      cookies.permanent[:logged_in_before] = true
      redirect_to root_url
    else
      redirect_to :back
    end
  end
  
  private
  
  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:name, :password)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @you_are_home = true
    cookies[:carousel_index] = 0
  end
  
  def scroll_to_top
  end
  
  def focus_to_section
    @section_id = params[:section_id]
    @close_menu = params[:close_menu]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def fa_icon icon, label='', size=''
    str = %Q[<i class="fa fa-#{icon}#{' ' + size if size.present?}"></i>] + " " + label
    return str.html_safe
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/app/_menu_items.html.erb
<% case section_id.gsub("_section", "") %>
  <% menu_items = when "services" %>
    <% [""] %>
  <% when "about_us" %>
    <% [""] %>
  <% when "projects" %>
    <% [""] %>
  <% when "clients" %>
    <% [""] %>
  <% when "contact_us" %>
    <% [""] %>
<% end %>

<div class="menu_items">
  <% for menu_item in menu_items  %>
    <div class="menu_item">
      <%= menu_item %>
    </div>
  <% end %>
</div>

app/views/app/_nav_bar.html.erb
<div class="nav_bar">
  <%= link_to (@you_are_home ? scroll_to_top_path : root_url), remote: @you_are_home do %>
    <%= image_tag "logo.png", class: :nav_logo %>
  <% end %>
  <% for section in ["Services", "About Us", "Projects", "Clients", "Contact Us"] %>
    <% section_id = section.downcase.gsub(" ", "_") + "_section" %>
    <%= link_to focus_to_section_path(section_id: section_id), remote: true do %>
      <div class="nav_section">
        <div class="nav_section_text">
          <%= section %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

<div class="nav_spacing"></div>

app/views/app/_nav_hover_detect.js.erb
function nav_hover_detect_<%= section_id %>() {
  section = $("#<%= section_id %>");
  if ($("#<%= section_id %>:hover").length != 0) {
    section.after("<%=j render "app/menu_items", section_id: section_id %>");
  }
}

app/views/app/_nav_menu.html.erb
<div class="nav_menu">
  <%= link_to '<i class="fa fa-bars fa-2x"></i>'.html_safe, toggle_menu_path,
    id: :toggle_menu_link, remote: true, title: "Main menu" %>
    
    
  <%= link_to (@you_are_home ? scroll_to_top_path : root_url), remote: @you_are_home do %>
    <%= image_tag "logo.png", class: :nav_menu_logo %>
  <% end %>

  <div id="nav_menu" hidden>
    <% for section in ["Services", "About Us", "Projects", "Clients", "Contact Us"] %>
      <% section_id = section.downcase.gsub(" ", "_") + "_section" %>
      <%= link_to section, focus_to_section_path(section_id: section_id, close_menu: "1"),
        remote: true, class: :standard_nav_menu_link %>
    <% end %>
  
    <% if current_user %>
    	<%= link_to fa_icon("sign-out", "Log out"), sessions_destroy_path, method: :delete,
    	  class: :standard_nav_menu_link, title: "Click here to destroy your cookie.",
    	  data: { confirm: "Are you sure?" } %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GSC Surveying, Inc.</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
</head>
<body>

<%= render "app/nav_menu" %>
<%= render "app/nav_bar" %>

<%= yield %>

</body>
</html>

app/views/pages/toggle_menu.js.erb
var nav_menu = $("#nav_menu");

<% unless @nav_menu_shown %>
  nav_menu.fadeIn();
<% else %>
  nav_menu.fadeOut();
<% end %>

app/views/posts/_carousel.html.erb
<div class="image_carousel">
  <%= link_to "<", carousel_scroll_path(direction: :left), remote: true, class: "top_left_link carousel_link" %>
  <%= link_to ">", carousel_scroll_path(direction: :right), remote: true, class: "bottom_right_link carousel_link" %>
  <div class="carousel_hider_left"></div><div class="carousel_hider_right"></div>
  <div id="carousel_images_anchor"></div>
  <div id="carousel_images">
    <% for image in images %>
      <%= render "posts/carousel_image", image: image.image %>
    <% end %>
  </div>
</div>

app/views/posts/_carousel_image.html.erb
<%= image_tag image, class: "carousel_image" %>

app/views/posts/_form.html.erb
<div class="card">
  <%= form_for(@post) do |f| %>

    <div align="center">
      <p>
        <%= f.text_area :body, placeholder: "Write your text here..." %>
      </p>
	    
		  Attach an image: <%= f.file_field :image %>
		  
	    <p>
        <button type="submit" name="commit" class="standard_form_button">
	        <b>Post <i class="fa fa-pencil"></i></b>
        </button>
      </p>
    </div>
  <% end %>
</div>

app/views/posts/carousel_scroll.js.erb
$(".carousel_image").<%= @point_to_add %>().after("<%=j render "posts/carousel_image", image: @image.image, id: @image_id %>");

$("#carousel_images").animate(
  { width: 500 },
  { duration: 1000 }
);

$(".carousel_image").<%= @point_to_remove %>().remove();

app/views/posts/new.html.erb
<%= render "posts/form" %>

app/views/users/_form.html.erb
<div class="card">
  <%= form_for(@user) do |f| %>
  	<%= link_to "Already signed up?", sessions_new_path, class: :top_right_link %>

    <div align="center">
      <p>
        <%= f.text_field :name, placeholder: "Username", class: :standard_text_field %>
        <%= f.password_field :password, placeholder: "Password", class: :standard_text_field %>
        <%= f.password_field :password_confirmation, placeholder: "Confirm password", class: :standard_text_field %>
      </p>
	    <p>
        <button type="submit" name="commit" class="standard_form_button">
	        <b>Sign up <i class="fa fa-pencil"></i></b>
        </button>
      </p>
    </div>

	  <div id="remember_me_check_box">
		  Remember me <%= check_box_tag :remember_me, 1, params[:remember_me] %>
	  </div>
  <% end %>
</div>

app/views/users/new.html.erb
<%= render "users/form" %>

app/views/welcome/focus_to_section.js.erb
<% if @close_menu.eql? "1" %>
  $("#nav_menu").fadeOut();
<% end %>

$('html,body').animate({
   scrollTop: $("#<%= @section_id %>").offset().top - 125
});

app/views/welcome/index.html.erb
<%= image_tag "map.jpg", width: "100%" %>

<div class="section_part" id="services_section">
  <div class= "services_parenta"> 
    <div class="gsc_construction_icon">
      <%= image_tag "icons/gsc_construction_icon.png", width: "110px" %>
      <p style= "color: black; max-width: 300px;">
        CONSTRUCTION
      </p>
    </div>
     
    <div class="gsc_3d_modelling_icon">
      <%= image_tag "icons/gsc_3d_modelling.png", width: "110px" %>
      <p style="color: black; max-width: 300px;">
        3D MODELING
      </p>
    </div>
   
    <div class="gsc_gps_icon">
      <%= image_tag "icons/gsc_gps.png", width: "110px" %>
      <p style= "color: black; max-width: 300px;">
        ONSITE TECHNICAL SUPPORT ON GPS MACHINE CONTROL
      </p>
    </div>
   
    <div class="location_survey_icon">
      <%= image_tag "icons/location_survey.png", width: "110px" %>
      <p style="color: black; max-width: 300px;">
        TOPOGRAPHIC SURVEYING
      </p>
    </div>
  </div>
 
  <div class="services_parentb">
    <div class="gsc_survey_icon">
      <%= image_tag "icons/gsc_survey.png", width: "110px" %>
      <p style="color: black; max-width: 300px;">
        HORIZONTAL AND VERTICAL CONTROL SURVEYS
      </p>
    </div>
   
    <div class="gsc_control_survey_icon">
      <%= image_tag "icons/gsc_control_survey.png", width: "110px" %>
      <p style="color: black; max-width: 300px;">
        LOCATION SURVEYS FOR ENGINEERING AND DESIGN
      </p>
    </div>

    <div class="other_alt_icon">
      <%= image_tag "icons/other_alt.png", width: "110px" %>
      <p style= "color: black; max-width: 300px;">
        OTHER SURVEYING SERVICES
      </p>
    </div>
  </div>
</div>

<div class="section_part" id="about_us_section">
 <h2 style="color:darkorange";> About Us</h2>
</div>

<div class="section_part" id="projects_section">
  <h2 style="color:darkblue";>Projects</h2>
</div>

<div class="section_part" id="clients_section">
 <h2 style="color: darkorange";> Clients</h2>
</div>

<div class="section_part" id="contact_us_section" >
  <h2>Contact Us</h2>
  <div class="company_emails">
    <p style= font-size:18px;>
      Greg S. Crowder, President
      Registered Land Surveyor
      greg@gscsurveying.com

      Benjamin Andrews
      ben@gscsurveying.com

      Austin McCleery
      austin@gscsurveying.com

      Liz Carpenter Bayer, Office Manager
      liz@gscsurveying.com
    </p>
  </div>
  <div class= "facebook_icon">
    <%= link_to "http://www.facebook.com" do %>
      <%= image_tag "icons/facebook.png", width: "40%" %>
    <% end %>
  </div>
  <div class="twitter_icon">
    <%= link_to "http://www.twitter.com" do %>
      <%= image_tag "icons/twitter.png", width: "40%" %>
    <% end %>
  </div>
  
  <div class="instagram_icon">
    <%= link_to "http://www.instagram.com" do %>
      <%= image_tag "icons/instagram.png", width: "40%" %>
    <% end %>
    </div>
  
  
  
  <div class="google_maps"><iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3234.7142925526628!2d-78.63260468473706!3d35.83148498015967!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89ac58ea71c6eb91%3A0x6b3df7bae78983ea!2sGSC+Surveying+Inc!5e0!3m2!1sen!2sus!4v1485914436090" width="400" height="300" frameborder="0" style="border:0" allowfullscreen></iframe></div>
</div>

<div align="center">
  <div align="center">
    <% unless current_user %>
      <p><%= link_to "Register", new_user_path, class: :white_link %></p>
      <p><%= link_to "Log in", sessions_new_path, class: :white_link %></p>
    <% else %>
      <p class="welcome_text">You are signed in.</p>
      <p class="welcome_text">Welcome, <%= current_user.name %>!</p>
      <%= link_to "Log out", sessions_destroy_path, method: :delete, class: :white_link %>
    <% end %>
  </div>
</div>

app/views/welcome/scroll_to_top.js.erb
$("html, body").animate({
  scrollTop: 0
},"slow");